---
- hosts: all
  sudo: true
  vars:
    # VAGRANT
    vagrant_home: /home/vagrant
    vagrant_owner: vagrant
    vagrant_group: vagrant
    # COMPOSER CONFIGURATIONS
    composer_vendor_dir: /home/vagrant/vendor
    composer_process_timeout: 2000
    composer_optimize_autoloader: 'true'
    composer_discard_changes: 'true'
    composer_github_protocols: ['https', 'ssh']
    # WEBSERVER CONFIGURATIONS
    document_root: /var/www/html
    # PROJECT CONFIGURATIONS
    project_path: /var/www/html/project
    # PHP
    php_short_open_tag: 'Off'
    php_asp_tags: 'Off'
    php_output_buffering: 4096
    php_zlib_output_compression: 'Off'
  pre_tasks:
    - name: Update APT Cache
      apt: update_cache=yes
  roles:
    - webserver
    - database
    - tools
